services:

  rabbitmq:
    profiles: [ 'multiprocess' ]
    image: rabbitmq:4
    networks:
      - local-network
    ports:
      - "35672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      start_period: 10s
      retries: 3

  spark:
    profiles: [ 'multiprocess' ]
    build:
      context: ./
      dockerfile: client_multiprocess/spark/Dockerfile
    networks:
      - local-network

  client-multiprocess-listener:
    profiles: [ 'multiprocess' ]
    build:
      context: ./
      dockerfile: client_multiprocess/listener/Dockerfile
    networks:
      - local-network
    environment:
      WS_URL: "wss://stream.binance.com:9443/ws/btcusdc@trade"
      LISTENER_PERIOD: 0
      BROKER_HOST: "rabbitmq"
    depends_on:
      rabbitmq:
        condition: service_healthy

  client-multiprocess-loader:
    profiles: [ 'OFFmultiprocess' ]
    build:
      context: ./
      dockerfile: client_multiprocess/loader/Dockerfile
    networks:
      - local-network
    environment:
      LISTENER_PERIOD: 0
      BROKER_HOST: "rabbitmq"
    depends_on:
      rabbitmq:
        condition: service_healthy

  client-multiprocess-consumer:
    profiles: [ 'multiprocess' ]
    build:
      context: ./
      dockerfile: client_multiprocess/consumer/Dockerfile
    networks:
      - local-network
    environment:
      LOGLEVEL: "INFO"
      CONSUMER_PERIOD: 0
      BROKER_HOST: "rabbitmq"
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  local-network:
    driver: bridge
