services:

  server:
    profiles: [ 'OFF' ]
    build:
      context: ./
      dockerfile: server/Dockerfile
    networks:
      - local-network
    ports:
      - "12345:12345"
    environment:
      WS_PORT: 12345
      LOG_LEVEL: "INFO"
      PERIOD: 1
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:12345/healthcheck" ]
      interval: 30s
      timeout: 30s
      start_period: 10s
      retries: 3

  rabbitmq:
    profiles: [ 'multiprocess' ]
    image: rabbitmq:4
    networks:
      - local-network
    ports:
      - "35672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      start_period: 10s
      retries: 3

  listener-1:
    profiles: [ 'multiprocess' ]
    build:
      context: ./
      dockerfile: listener/Dockerfile
    networks:
      - local-network
    environment:
      WS_URL: "wss://stream.binance.com:9443/ws/btcusdc@trade"
      PERIOD: 0
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "direct"
      BROKER_ROUTING_KEY: "trade"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy

  listener-2:
    profiles: [ 'multiprocess' ]
    build:
      context: ./
      dockerfile: listener/Dockerfile
    networks:
      - local-network
    environment:
      WS_URL: "wss://stream.binance.com:9443/ws/bnbusdc@kline_1m"
      PERIOD: 0
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "direct"
      BROKER_ROUTING_KEY: "kline_1m"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy

  fetcher:
    profiles: [ 'OFF' ]
    build:
      context: ./
      dockerfile: fetcher/Dockerfile
    networks:
      - local-network
    environment:
      HTTP_URL: "https://api.frankfurter.dev/v1/latest?base=USD"
      PERIOD: 10
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "direct"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    profiles: [ 'multiprocess' ]
    build:
      context: ./
      dockerfile: consumer/Dockerfile
    networks:
      - local-network
    environment:
      PERIOD: 0
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "direct"
      BROKER_ROUTING_KEY: "trade, kline_1m"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  local-network:
    driver: bridge
