services:

  rabbitmq:
    profiles: [ 'real-world', 'test-LB' ]
    image: rabbitmq:4
    networks:
      - local-network
    ports:
      - "35672:5672"
    healthcheck:
      test: >
        bash -lc "rabbitmqctl await_startup &&
                  rabbitmq-diagnostics -q check_running &&
                  rabbitmq-diagnostics -q check_port_connectivity" 
      interval: 30s
      timeout: 30s
      start_period: 20s
      retries: 3

  listener-binance-kline1m:
    profiles: [ 'real-world' ]
    build:
      context: ../
      dockerfile: build/listener/Dockerfile
    networks:
      - local-network
    environment:
      URL: "wss://stream.binance.com:9443/ws/bnbusdc@kline_1m"
      SLEEP: 0.1
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "direct"
      BROKER_ROUTING_KEY_OUT: "kline_1m"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy

  listener-binance-account:
    profiles: [ 'real-world', 'test-LB' ]
    build:
      context: ../
      dockerfile: build/listener/Dockerfile
    networks:
      - local-network
    env_file: ../.env
    environment:
      URL: "wss://stream.binance.com:9443/ws"
      AUTHN_URL: "https://api.binance.com/api/v3/userDataStream"
      SLEEP: 0
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "direct"
      BROKER_ROUTING_KEY_OUT: "account.orders"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy

  listener-http:
    profiles: [ 'OFFreal-world' ]
    build:
      context: ../
      dockerfile: build/listener/Dockerfile
    networks:
      - local-network
    environment:
      URL: "https://api.frankfurter.dev/v1/latest?base=USD"
      SLEEP: 1
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "direct"
      BROKER_ROUTING_KEY_OUT: "frankfurter"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy

  postgres:
    profiles: [ 'real-world', 'pgonly' ]
    image: postgres:16
    env_file: ./initdb/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # ? do sta?
      - ./initdb:/docker-entrypoint-initdb.d:ro # auto roles on first init
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_orders" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks: [ local-network ]

  analyst:
    profiles: [ 'real-world' ]
    build:
      context: ../
      dockerfile: build/analyst/Dockerfile
    networks: [ local-network ]
    environment:
      BROKER_HOST: rabbitmq # this matches the mq service name
      BROKER_EXCHANGE: exchange
      BROKER_EXCHANGE_TYPE: direct
      BROKER_ROUTING_KEY_IN: "kline_1m, account.exec_updates"
      BROKER_ROUTING_KEY_OUT: orders.outgoing
      BROKER_ROUTING_KEY_ACCOUNTANT: exchange_response
      ANALYST_ID: analyst_1
      SLEEP: 10
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy

  db-writer:
    profiles: [ 'OFFreal-world' ]
    build:
      context: ../
      dockerfile: build/db_writer/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://app_writer:app_writer@postgres:5432/db_orders
      SLEEP: 0
      LOG_LEVEL: "INFO"
      BROKER_HOST: rabbitmq
      BROKER_EXCHANGE: exchange
      BROKER_EXCHANGE_TYPE: direct
      # BROKER_ROUTING_KEY_IN: outgoing_orders # what about this?
      BROKER_ROUTING_KEY_IN: exchange_response # must match accountant      
    networks: [ local-network ]
    restart: unless-stopped

  transmitter-binance-http:
    profiles: [ 'real-world' ]
    build:
      context: ../
      dockerfile: build/transmitter/Dockerfile
    networks:
      - local-network
    env_file: ../.env
    environment:
      URL: "https://api.binance.com"
      SLEEP: 0
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "direct"
      BROKER_ROUTING_KEY_IN: "outgoing_orders"
      BROKER_ROUTING_KEY_OUT: "exchange_response"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy

  accountant:
    profiles: [ 'real-world' ]
    build:
      context: ../
      dockerfile: build/accountant/Dockerfile
    networks:
      - local-network
    environment:
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "direct"
      BROKER_ROUTING_KEY_IN: "account.orders, orders.outgoing"
      BROKER_ROUTING_KEY_OUT: "account.exec_updates"
      SLEEP: 0
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

networks:
  local-network:
    driver: bridge

volumes:
  pgdata:


