services:

  server:
    annotations:
      description: "sources"
    build:
      context: ../
      dockerfile: build/server/Dockerfile
    networks:
      - local-network
    ports:
      - "12345:12345"
    environment:
      WS_PORT: 12345
      LOG_LEVEL: "INFO"
      SLEEP: 1
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:12345/healthcheck" ]
      interval: 30s
      timeout: 30s
      start_period: 10s
      retries: 3

  listener-ws:
    annotations:
      description: "websocket connection to source"
    build:
      context: ../
      dockerfile: build/listener/Dockerfile
    networks:
      - local-network
    environment:
      URL: "ws://server:12345/ws"
      SLEEP: 0
      BROKER_BACKEND: "rabbitmq"
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "topic"
      BROKER_ROUTING_KEY_OUT: "source.ws"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_healthy

  listener-http:
    annotations:
      description: "HTTP requests to source"
    build:
      context: ../
      dockerfile: build/listener/Dockerfile
    networks:
      - local-network
    environment:
      URL: "http://server:12345/http"
      SLEEP: 5
      BROKER_BACKEND: "rabbitmq"
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "topic"
      BROKER_ROUTING_KEY_OUT: "source.http"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_healthy

  queue-logger:
    annotations:
      description: "log all sources and avg of source.ws"
    build:
      context: ../
      dockerfile: build/queue_logger/Dockerfile
    networks:
      - local-network
    environment:
      SLEEP: 0
      BROKER_BACKEND: "rabbitmq"
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "topic"
      BROKER_ROUTING_KEY_IN: "source.*, transformed.avg"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_healthy

  transformer:
    annotations:
      description: "evaluate avg and std of source.ws"
    build:
      context: ../
      dockerfile: build/transformer/Dockerfile
    networks:
      - local-network
    environment:
      SLEEP: 0
      BROKER_BACKEND: "rabbitmq"
      BROKER_HOST: "rabbitmq"
      BROKER_EXCHANGE: "exchange"
      BROKER_EXCHANGE_TYPE: "topic"
      BROKER_ROUTING_KEY_IN: "source.ws"
      BROKER_ROUTING_KEY_OUT: "transformed.std, transformed.avg"
      LOG_LEVEL: "INFO"
    depends_on:
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_healthy

  rabbitmq:
    annotations:
      description: "message broker"
    image: rabbitmq:4
    networks:
      - local-network
    ports:
      - "35672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      start_period: 20s
      retries: 3

networks:
  local-network:
    driver: bridge
